export const userData = [
  { id: 1, name: "Adams", isActive: true },
  { id: 2, name: "Baker", isActive: false },
  { id: 3, name: "Clark", isActive: false },
  { id: 4, name: "Davis", isActive: true },
  { id: 5, name: "Evans", isActive: true },
  { id: 6, name: "Jack", isActive: true },
  { id: 7, name: "Frank", isActive: false },
  { id: 8, name: "Ghosh", isActive: true },
  { id: 9, name: "Hills", isActive: false },
  { id: 10, name: "Irwin", isActive: true },
  { id: 11, name: "Jones", isActive: true },
  { id: 12, name: "Reily", isActive: false },
  { id: 13, name: "Smith", isActive: true },
  { id: 14, name: "Jackson", isActive: false },
  { id: 15, name: "David", isActive: false },
];
